firstname = input("Enter first name: ")
lastname = input("Enter last name: ")
middlename = input ("Enter middle name: ")
bday = input("Enter your birthdate: ")
gender = input("Enter your gender: ")
address = input("Enter your address: ")
course = input("Enter your current course: ")
yearlvl = input("Enter your current year level: ")

print("")
print("First Name: ", firstname)
print("Last Name: ", lastname)
print("Middle Name: ", middlename)
print("Birthday: ", bday)
print("Gender: ", gender)
print("Address: ", address)
print("Course: ", course)
print("Year Level: ", yearlvl)